version: '2'
services:
  # Web Proxy
  proxy:
    build: caddy
    links:
    - api
    ports:
    - "80:80"
    - "443:443"
  # Our Servers
  api:
    build: api
    links:
    - redis
  # Other Services
  opensmtpd:
    image: qjcg/opensmtpd
  redis:
    image: redis:alpine
    volumes:
    - /data
